apiVersion: apps/v1
kind: Deployment
metadata:
  name: shizgara-deployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: shizgara-nodejs-app
 template:
   metadata:
     labels:
       app: shizgara-nodejs-app
   spec:                  
     containers:
     - name: shizgara-nodejs-app
       image: shizgara/simple_react_app:latest
       ports:
       - containerPort: 3001