apiVersion: apps/v1
kind: Deployment
metadata:
  name: shizgara-deployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: shizgara-nodejs-app
 template:
   metadata:
     labels:
       app: shizgara-nodejs-app
   spec:
     containers:
     - name: simple-react-app
       image: docker.io/shizgara/simple_react_app:latest
       ports:
       - containerPort: 3000
 ---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: shizgara-nodejs-app
  ports:
    - port: 80
      targetPort: 3000
