apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  serviceAccountName: tkn-sa
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params: # звідси ми передаємо value в оголошені змінні в pipeline.yaml 
  - name: repo-url
    value: https://github.com/shizgara/simple_react_app_docker.git
  - name: image-reference
    value: docker.io/shizgara/simple_react_app:latest
  - name: pathToYamlFile
    value: manifest/Deployment.yaml
